#!/bin/bash
#############################################################################################
#																							#
#	Autor: Sifiro		  			   														#
#   Version: 1.0				  			   												#
#   Licencia: GPL 3.0																		#
#   Codigo Fuente: https://github.com/sifiro/OpenSSH-Installer-Script 						#
#																							#
#############################################################################################
clear
##COLORES
GREEN='\033[0;32m'
RED='\033[0;31m'
NORM='\033[0m'
## Directorio de librerias
files="$PWD/files"
echo "----------------------------------------------------------------"
echo "OpenSSH Installer Script by Sifiro"
echo "----------------------------------------------------------------"
##sleep 1
echo "Se Procedera a hacer un chequeo de requisitos e integridad de los ficheros"
read
## Mas Informacion en Su Fichero
source $files/check ## Carga la Libreria Check
check ## Carga la Funcion Check
##################################################

if [ ${check_status}[0]} -ne -1  ];then
##################################################
source $files/menu
source $files/instal
source $files/configure
##################################################
menu ##Carga el Menu
else echo "Sistema Operativo no Soportado. Consulte con Sifiro o vaya a hacer un pull request"
fi
