#!/bin/bash
#############################################################################################
#																							#
#	Autor: Sifiro		  			   														#
#   Version: 1.0				  			   												#
#   Licencia: GPL 3.0																		#
#   Codigo Fuente: https://github.com/sifiro/OpenSSH-Installer-Script 						#
#																							#
#############################################################################################
#############################################################################################
#																							#
# Check - Libreria de Control de Ficheros, Integracion y Deteccion de la Diestro GNU/Linux 	#
#																							# 
# Su Resultado es un Array llamado check_status de longitud 6 elementos					   	#				
# Defecto: -1 0 0 0 0 0																		#
# El Primer Elemento identifica el Sistema Operativo										#
# -1 = No Compatible # 0 = Gentoo # 1= Ubuntu # 2=Debian									#
# los demas elementos son la disponibilidad de los ficheros representado por				#
# 0 = No Disponible # 1 = Disponible 														#
#																							#
#############################################################################################
function check () {
## Variables Iniciales
names=("menu" "instal" "configure" "files" "uninstall" "lib")
files_sha256=(ecccfaf484c708a5df2db3aba8d9aa2b7f25d9af733abb92d8e3480e477de8c0 078c15168770e8d950b68d12d5758373776f94175e9fd2c0ef98c7ab478972f1 2f4c2302cffda06d8921f2ba97e6bc8895dd0f1fe6d70aacf6f1d2e5f8f2b4d9 dc77c1d1fed4ea57215f6551e978351fa56f3e73a7ca0f64886248cd1332d3a7 e84b3e87db9a2c798b34051e9cb789434ebbe85d4acd4c2edf34ca4112f0839d 7179eee23557ef7156d2d3979dd4da5466ddf205e98e793abe7e61a236fbf09c)
# 0 -- Diestro Compatible 1-5 Check de Ficheros
# El Primer elemento del Array indica el Sistema operativo compatible que se usara y apartir de ahi su gestor de paquetes
check_status=(-1 0 0 0 0 0);
support_dist=("Gentoo" "Ubuntu" "Debian");
echo "Chequeando Sistema Operativo"
linux=`lsb_release -i | cut -f2`
sleep 1
echo "Sistema Operativo Seleccionando: $linux"
echo "Comprobando Compatibilidad con el Script"
sleep 1
for((i=0;i<${#support_dist[*]};++i))
	do
		if [ "$linux" = "${support_dist[i]}" ];then 
			check_status[0]=$i
			echo "Sistema Operativo Compatible"
			break
		fi
done

for((i=0;i<${#names[*]};++i))
	do
	directory=files/${names[i]}
	echo -n Chequeando ${names[i]}
			if [ -f $directory ] ;then 
				echo -n ".";
				sleep 1
				echo -n ".";
				if [ "${files_sha256[i]}" = "`sha256sum $directory| cut -d' ' -f1`" ];then
					sleep 1
					check_status[`expr $i + 1`]=1
					echo -e ". ${GREEN}OK${NORM}";
					else 
						echo -e "  ${RED}FAIL"
						echo -e "ERROR,PROBLEMAS CON LA INTEGRACION DEL FICHERO${NORM}"
				fi
				else 
				echo -e "  ${RED}FAIL"
				echo -e " ERROR, FICHERO NO EXISTENTE${NORM}"
			fi
	done
}
