#!/bin/bash
function files(){
allow="/etc/hosts.allow"
deny="/etc/hosts.deny"
file_a="$workdir/hosts.allow"
file_a="$workdir/hosts.deny"
su_metodo "cp $allow $file_a"
su_metodo "chown $USER.$USER $file_a"
su_metodo "cp $deny $file_d"
su_metodo "chown $USER.$USER $file_d"

if [ ${#ip[*]} -ne 0 ];then 
sust 'sshd:' "${ip[*]}" $file_a
else
ip=();
ip_invalid=-1;
echo "Introduce las Direcciones IP que desea permitir conexion SSH"
echo "pulsa 'q' para terminar"
until [ "$op" = "q" ]
do
read op
if [ "$op" != "q"  ];
        then ip_check $op
        if [ $ip_invalid -eq 0 ];then 
                ip="${ip[*]} $op"
                echo "Direccion $op añadida"
        else echo "Direccion IP No Valida"
        fi
fi
done
sust 'sshd:' "${ìp[*]}" $file_a
sust 'ALL: ' "*" $file_d
su_metodo "mv $allow /etc/hosts.allow.bak"
su_metodo "mv $allow /etc/hosts.deny.bak"
su_metodo "cp $file_a $allow"
su_metodo "cp $file_d $deny"
fi
}
