#!/bin/bash
clear
##Flag
##check_status=(1 1 1 1 1 1 1);

function instal_go (){
echo "Se Procedera a Instalar OpenSSH, este proceso es automatico"
sleep 1
echo "Pero antes necesitamos tu contraseña para continuar"
su-metodo "$pm $update;$pm $instal $package"
}

function instal (){
set_env
opcion="";
while [ opcion != "" ]
do
echo "Esta Operacion requerira conexion a Internet"
echo "Se Comprobara que tengas Conexion a Internet"
echo "Quieres Comenzar?"
echo "1=Si o 2=No"
read opcion
case "$opcion" in
	1)wan_test instal_go;;
	2)break;;
esac
done
}

