#!/bin/bash
##Flag
function instal_go (){
clear
echo "Se Procedera a Instalar OpenSSH, este proceso es automatico"
sleep 1
echo "Pero antes necesitamos tu contraseña para continuar"
su_metodo "$pm $update"
su_metodo "$pm $instal $package"
}

function instal (){
clear
set_env
opcion="";
while [ true ]
do
echo "Esta Operacion requerira conexion a Internet"
echo "Se Comprobara que tengas Conexion a Internet"
echo "Quieres Comenzar?[Si/S/Yes/Y N/No]"
read opcion
if [ "$opcion" = "S" ] || [ "$opcion" = "s" ]  || [ "$opcion" = "Si" ] || [ "$opcion" = "Y" ] || [ "$opcion" = "Yes" ];then wan_check instal_go;break;
elif [ "$opcion" = "No" ] || [ "$opcion" = "n" ] || [ "$opcion" = "N" ];then break
else echo "Perdon?, Escriba de nuevo"
fi
done
}
