#!/bin/bash
function uninstall () {
set_env
while [ true ]
do
echo "¿Vamos a proceder a desinstalar OpenSSH esta seguro?"
read opcion
if [ "$opcion" = "S" ] || [ "$opcion" = "Si" ] || [ "$opcion" = "Y" ] || [ "$opcion" = "Yes" ];then wan_check uninstall_go;break;
elif [ "$opcion" = "No" ] || [ "$opcion" = "N" ];then break;
else echo "Perdon?, Escriba de nuevo"
fi
done
}
function uninstall_go (){
echo "Se Procedera a Desinstalar OpenSSH, este proceso es automatico"
sleep 1
echo "Pero antes necesitamos tu contraseña para continuar"
echo "$pm $purge $package"
su_metodo "$pm $purge $package"
#allow="/etc/hosts.allow"
#deny="/etc/hosts.deny"
#file_a="$workdir/hosts.allow"
#file_d="$workdir/hosts.deny"
#su_metodo "cp $allow $file_a"
#su_metodo "chown $USER.$USER $file_a"
#su_metodo "cp $deny $file_d"
#su_metodo "chown $USER.$USER $file_d"
#sust 'sshd:' "" $file_a
#sust 'ALL: ' "" $file_b
#su_metodo "mv $allow /etc/hosts.allow.bak"
#su_metodo "mv $allow /etc/hosts.deny.bak"
#su_metodo "cp $file_a $allow"
#su_metodo "cp $file_d $deny"
}
